services:
  apache:
    restart: always
    build:
      context: .
    ports:
      - '8200:80'
    depends_on:
      mariadb:
        condition: service_healthy
  mercure:
    image: dunglas/mercure
    restart: always
    ports:
      - "3000:80"
    environment:
      SERVER_NAME: ':80'
      MERCURE_JWT_SECRET: ${MERCURE_JWT_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: "${MERCURE_PUBLISHER_JWT_KEY}"
      MERCURE_SUBSCRIBER_JWT_KEY: "${MERCURE_SUBSCRIBER_JWT_KEY}"
      MERCURE_CORS_ALLOWED_ORIGINS: "${MERCURE_CORS_ALLOWED_ORIGINS}"
      MERCURE_ALLOW_ANONYMOUS: "${MERCURE_ALLOW_ANONYMOUS}"
      MERCURE_EXTRA_DIRECTIVES: |
        jwt_key "${MERCURE_JWT_SECRET}"
  mariadb:
    image: mariadb:10
    restart: always
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: stat-board
    ports:
      - '3306:3306'
    volumes:
      - mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "127.0.0.1:8080:80"
    environment:
      PMA_HOST: mariadb
    depends_on:
      mariadb:
        condition: service_healthy
volumes:
  mariadb:

